validacion de fechas anda

diff --git a/grupo09/PROCEP b/grupo09/PROCEP
--- a/grupo09/PROCEP
+++ b/grupo09/PROCEP
@@ -73,8 +73,8 @@ function loop {
                 while IFS='' read -r linea || [[ -n "$linea" ]]; do
                     echo "Text read from file: $linea"
                     registro_valido=true
+                    formato_valido=true
                     IFS=';' read -ra valores <<< "$linea"
-
                     # 2) Validar los campos
 
                     #Validación Centro de Presupuesto: El centro de presupuesto debe existir en el maestro de centros
@@ -119,6 +119,37 @@ function loop {
                         if [ "${valores[4]}" == "${trimestre[1]}" ]; then
                             echo "encontrado trimestre: ${valores[4]}"
                             encontrado=true
+
+                            #Validación de Fecha: la fecha indicada en el registro debe ser una fecha valida;
+                            fecha=${valores[1]}
+                            # Regex compleja. Lo que hago es convertir el formato de aaaammdd a mm/dd/aaaa para poder validar con date
+                            formato_pedido=$(echo $fecha} | sed 's/\([0-9]\{4\}\)\([0-9]\{2\}\)\([0-9]\{2\}\)/\2\/\3\/\1/')
+                            date "+%m/%d/%Y" -d $formato_pedido > /dev/null  2>&1
+                            valida=$?
+                            if [ "$valida" = true ]; then
+                                formato_valido=false
+                                echo "Fecha formato invalida: $fecha"
+                                break
+                            fi
+#                            desde=$(echo ${valores[2]} | sed 's/\([0-9]\{2\}\)\/\([0-9]\{2\}\)\/\([0-9]\{4\}\)/\3\2\1/')
+#                            hasta=$(echo ${valores[3]} | sed 's/\([0-9]\{2\}\)\/\([0-9]\{2\}\)\/\([0-9]\{4\}\)/\3\2\1/')
+                            desde=${valores[2]}
+                            hasta=${valores[3]}
+                            if [ "$fecha" \< "$desde" ] || [ "$fecha" = "$hasta" ] || [ "$fecha" \> "$hasta" ]; then
+                                formato_valido=false
+                                echo "Fecha desde o hasta invalida: $fecha"
+                                break
+                            fi
+                            hoy=$(date "+%Y%m%d")
+                            if [ $fecha \> $hoy ]; then
+                                formato_valido=false
+                                echo "Fecha hoy invalida: $fecha"
+                                break
+                            fi
+                            # menor o igual a la
+                            #fecha del nombre del archivo y estar comprendida entre la fecha de inicio del trimestre
+                            #(FDESDE_TRI) y la fecha de fin del trimestre (FHASTA_TRI)
+
                             break
                         fi
                     done < "$DIRMAE/trimestres.csv"
@@ -128,11 +159,10 @@ function loop {
                         registro_valido=false
                     fi
 
-                    #Validación de Fecha: la fecha indicada en el registro debe ser una fecha valida; menor o igual a la
-                    #fecha del nombre del archivo y estar comprendida entre la fecha de inicio del trimestre
-                    #(FDESDE_TRI) y la fecha de fin del trimestre (FHASTA_TRI)
-
-
+                    if [ "$formato_valido" = false ]; then
+                        echo "Fecha invalida: ${valores[1]}"
+                        registro_valido=false
+                    fi
 
                     #Validación de Gasto: el importe de gasto debe ser mayor a cero.
                     if [ ${valores[5]} < 0 ]; then
